package com.rts.gui_final;

import com.rts.dao.daofactory.MySQLDAOFactory;
import com.rts.dao.interfaces.RiskTreatmentDao;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;



import com.rts.pojoclasses.*;
import com.rts.util.Config;

import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Risk_TreatmentFrame.java
 *
 * Created on Aug 23, 2012, 3:08:40 PM
 */

/**
 *
 * @author bhandrah
 */
public class Risk_TreatmentFrame extends javax.swing.JFrame {

    /** Creates new form Risk_TreatmentFrame */
    public Risk_TreatmentFrame() {
        initComponents();
        loadTable(jTableRisksTreatmentRegister);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAddRiskTreatment = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonReset2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRisksTreatmentRegister = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 255, 255)));

        jTableAddRiskTreatment.setAutoCreateRowSorter(true);
        jTableAddRiskTreatment.setBackground(new java.awt.Color(255, 204, 204));
        jTableAddRiskTreatment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Asset Name", "Threat", "Vulnerability", "Risk Category", "Risk Exposure", "Risk Treatment Approach", "Descision Reason", "Comment", "RiskEvaluationId", "ThreatVulnId", "ThreatId", "VulnId", "AssetId"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAddRiskTreatment.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBoxAssetList));
        Config cg=new Config();
        jTableAddRiskTreatment.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(
            new JComboBox(new DefaultComboBoxModel(new String[] {
                cg.arr1[0],
                cg.arr1[1],
                cg.arr1[2],
                cg.arr1[3]

            }))));
            jTableAddRiskTreatment.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTableAddRiskTreatmentMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTableAddRiskTreatment);
            jTableAddRiskTreatment.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableAddRiskTreatment.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTableAddRiskTreatment.getColumnModel().getColumn(8).setMinWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(8).setPreferredWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(8).setMaxWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(9).setMinWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(9).setPreferredWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(9).setMaxWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(10).setMinWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(10).setPreferredWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(10).setMaxWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(11).setMinWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(11).setPreferredWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(11).setMaxWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(12).setMinWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(12).setPreferredWidth(0);
            jTableAddRiskTreatment.getColumnModel().getColumn(12).setMaxWidth(0);

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
            jLabel2.setText("Enter Risk Treatment");

            jButton1.setText("Add");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButtonReset2.setText("Reset");
            jButtonReset2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonReset2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(355, 355, 355)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonReset2)))
                    .addContainerGap(356, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButtonReset2))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel2.setBackground(new java.awt.Color(255, 255, 255));
            jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 204, 204)));

            jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
            jLabel3.setText("Risk Treatment");

            jTableRisksTreatmentRegister.setAutoCreateRowSorter(true);
            jTableRisksTreatmentRegister.setBackground(new java.awt.Color(204, 255, 255));
            jTableRisksTreatmentRegister.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {new Boolean(false), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                    "", "Index", "Asset Name", "Threat", "Vulnerability", "Risk Category", "Risk Exposure", "Risk Treatment", "Description", "Comment", "RiskEvaluationId", "ThreatVulnId", "ThreatId", "VulnId", "AssetId", "RiskTreatmentId"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
                };
                boolean[] canEdit = new boolean [] {
                    true, false, true, false, false, false, false, true, true, true, false, false, false, false, false, true
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            TableColumn tc = jTableRisksTreatmentRegister.getColumnModel().getColumn(0);
            tc.setCellEditor(jTableRisksTreatmentRegister.getDefaultEditor(Boolean.class));
            tc.setCellRenderer(jTableRisksTreatmentRegister.getDefaultRenderer(Boolean.class));
            jTableRisksTreatmentRegister.addMouseListener(new MyMouseListener());
            it = new MyItemListener();
            cbh = new CheckBoxHeader(it);
            tc.setHeaderRenderer(cbh);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(jComboBoxAssetList));
            jScrollPane2.setViewportView(jTableRisksTreatmentRegister);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(10).setMinWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(10).setPreferredWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(10).setMaxWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(11).setMinWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(11).setPreferredWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(11).setMaxWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(12).setMinWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(12).setPreferredWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(12).setMaxWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(13).setMinWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(13).setPreferredWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(13).setMaxWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(14).setMinWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(14).setPreferredWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(14).setMaxWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(15).setMinWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(15).setPreferredWidth(0);
            jTableRisksTreatmentRegister.getColumnModel().getColumn(15).setMaxWidth(0);

            jButton2.setText("Update");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton6.setText("Delete");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(367, 367, 367)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton2)
                            .addGap(19, 19, 19)
                            .addComponent(jButton6))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(23, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20))
            );

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        int res=-1; // To know the Database Operation Status
        List<RiskTreatment> riskTreatment = new ArrayList<RiskTreatment>();
        for(int i=0;i<jTableAddRiskTreatment.getRowCount();i++){
            if(jTableAddRiskTreatment.getValueAt(i, 1)!=null && jTableAddRiskTreatment.getValueAt(i, 6)!=null) {
            res=-1;
            //System.out.println("Risks:"+jTableAddRiskTreatment.getValueAt(0, 0));
            riskTreatment.add(readTableRow(jTableAddRiskTreatment, i));
            System.out.println("Abt to read Row:"+i);
            if(riskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getThreats().getThreatName()==null ||
                    riskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getVulnerabilities().getVulnarabilityName()==null) {
                JOptionPane.showConfirmDialog(this,"Error", "Please select Threat and vulnerability for Row: "+i,JOptionPane.DEFAULT_OPTION);
                return;
            }
            if(riskTreatment.get(i).getRiskEvaluation().getRiskCategory()==null ||
                    riskTreatment.get(i).getRiskEvaluation().getRiskExposure()==0 ) {
                JOptionPane.showConfirmDialog(this, "Please make sure Category, Exposure are entered for Row: "+i,"Error",JOptionPane.DEFAULT_OPTION);
                return;
            }

         res=MySQLDAOFactory.getDAOFactory().getRiskTreatmentDao().insertRiskTreatment(riskTreatment.get(i));
         System.out.println("Insersion Result:"+res);
        }
        }
        //System.out.println("Waiting here");
        if(res!=-1){

           JOptionPane.showConfirmDialog(this, "Data Inserted into Database Successfully!!","Success",JOptionPane.DEFAULT_OPTION);
           loadTable(jTableRisksTreatmentRegister);
        }
   

    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
            // TODO add your handling code here:
        RiskTreatment riskTreatment = new RiskTreatment();
        //AssetsThreatsVuln asv = new AssetsThreatsVuln();
        String rows=null;
        for(int i=0;i<jTableRisksTreatmentRegister.getRowCount();i++){
            if((Boolean)jTableRisksTreatmentRegister.getValueAt(i, 0)==true){
                riskTreatment=readTableRow(jTableRisksTreatmentRegister, i);
                //System.out.println("Threat Type to be Updated:"+riskTreatment.getThreats().getThreatType());
                if(jTableRisksTreatmentRegister.getValueAt(i, 3)==null||jTableRisksTreatmentRegister.getValueAt(i, 6)==null
                      ||  jTableRisksTreatmentRegister.getValueAt(i, 5)==null){
                    JOptionPane.showConfirmDialog(this, "Please Fill All the Columns","Error",JOptionPane.DEFAULT_OPTION);
                } else {

                    int res = MySQLDAOFactory.getDAOFactory().getRiskTreatmentDao().insertRiskTreatment(riskTreatment);
                    if(res!=-1){
                        if(rows==null){ rows = ""+(i+1);}
                        else
                           rows=rows+","+(i+1);
                    }
                }
            }
        }
        if(rows!=null) {
        JOptionPane.showConfirmDialog(this, "Data Updated Successfully for Rows:"+rows,"Success",JOptionPane.DEFAULT_OPTION);
        loadTable(jTableRisksTreatmentRegister);
        for(int i=0;i<jTableRisksTreatmentRegister.getRowCount();i++){ jTableRisksTreatmentRegister.setValueAt(false, i, 0);}
        }

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            // TODO add your handling code here:
        int startIndex = -1;
        RiskTreatmentDao riskTreatmentDAO = MySQLDAOFactory.getDAOFactory().getRiskTreatmentDao();
        RiskTreatment riskTreatment = new RiskTreatment();
        Boolean[] selectColumnVal = new Boolean[jTableRisksTreatmentRegister.getModel().getRowCount()];

        for (int i = 0; i < jTableRisksTreatmentRegister.getModel().getRowCount(); i++) {
            selectColumnVal[i] = (Boolean) jTableRisksTreatmentRegister.getValueAt(i, 0);
        }

        for (int i = (selectColumnVal.length - 1); i >= 0; i--) {
            if (selectColumnVal[i] == true) {
                startIndex = i;

                System.out.println("Row To be Deleted: " + i);
                if (jTableRisksTreatmentRegister.getValueAt(i, 15)==null) {
                    DefaultTableModel model = (DefaultTableModel) jTableRisksTreatmentRegister.getModel();
                    model.removeRow(i);
                    continue;
                } else {
                    riskTreatment = readTableRow(jTableRisksTreatmentRegister,i);
                    int row = riskTreatmentDAO.deleteRiskTreatment(riskTreatment);
                    if (row == 0) {
                        System.out.println("Doesn't deleted any row!");
                    } else if (row != 0) {
                        System.out.println("Deleted Row: " + row);
                        DefaultTableModel model = (DefaultTableModel) jTableRisksTreatmentRegister.getModel();
                        model.removeRow(i);
                    } else if (row == -1) {
                        System.out.println("Error in executing Query");
                    }
                    loadTable(jTableRisksTreatmentRegister);
                }
            }
        }
//   System.out.println("start index "+startIndex+" total rows:"+jTable2.getModel().getRowCount());
        for (int i = startIndex; i <= jTableRisksTreatmentRegister.getModel().getRowCount(); i++) {
            if(i>0){
   //         System.out.println("setting " + i + " at " + i);
            jTableRisksTreatmentRegister.setValueAt(i, i - 1, 1);
            }
        }


}//GEN-LAST:event_jButton6ActionPerformed

private void jTableAddRiskTreatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAddRiskTreatmentMouseClicked
    // TODO add your handling code here:
            String assetName=null;
        int assetId=0;
        float assetValue=0;

        List<AssetsThreatsVuln> atvList = new ArrayList<AssetsThreatsVuln>();
        List<RiskEvaluation> riskEvaluation = new ArrayList<RiskEvaluation>();
        List<RiskTreatment> riskTreatment = new ArrayList<RiskTreatment>();

        int row = jTableAddRiskTreatment.getSelectedRow();
        if(jTableAddRiskTreatment.getSelectedRowCount()==1){
            if(jTableAddRiskTreatment.getSelectedColumn()==1){
                assetName=(String)jTableAddRiskTreatment.getValueAt(jTableAddRiskTreatment.getSelectedRow(), 0);
                //Fetch corresponding AssetValue and AssetId based on AssetName and ProjectId.
                if(assetName!=null) {
                    List<Assets> aList=new ArrayList<Assets>();
                    //Also Add where ProjectId == projectId clause in the below Query.
                    aList=MySQLDAOFactory.getDAOFactory().getAssetsDao().fetchAssetsListFromDb("from Assets where assetsName='"+assetName+"'");
                    assetId=(int)aList.get(0).getAssetId();
                    //assetValue=aList.get(0).getAssetsValue();

                    

                    //get Threats and Vulnarabilities.
                    String query="from AssetsThreatsVuln atv where atv.assets.assetId="+assetId;
                    atvList = MySQLDAOFactory.getDAOFactory().getAssetsThreatsVulnDao().fetchAssetsThreatsVuln(query);
                    //Load all the Threats and vuln into AddTable.
                   // System.out.println("Number of assets Records"+atvList.size());
                    for(int i=0;i<atvList.size();i++){
                        //Add Rows if required in the table.
                        if ( (jTableAddRiskTreatment.getModel().getRowCount()-jTableAddRiskTreatment.getSelectedRow()) < atvList.size() ) {
                            @SuppressWarnings("BooleanConstructorCall")
                            Object[][] rowData = {{null, null, null, null,null,null,null, null, null, null,null,null}};
                            DefaultTableModel model = (DefaultTableModel) jTableAddRiskTreatment.getModel();
                            model.addRow(rowData[0]);
                            if ((jTableAddRiskTreatment.getModel().getRowCount() - 1) == atvList.size()) {
                                //model.setValueAt(table.getModel().getRowCount(), table.getModel().getRowCount() - 1, 1);
                                //index++;
                                model.setValueAt(row+1,row+i,1);
                            }
                        }
                        String q="from RiskEvaluation re where re.assetsThreatsVuln.assetsThreatsVulnId="+atvList.get(i).getAssetsThreatsVulnId();
                        riskEvaluation=MySQLDAOFactory.getDAOFactory().getRiskEvaluationDao().fetchRiskEvaluation(q);
                        System.out.println("Entering AssetName"+assetName+" at Row:"+(row+i));
                        jTableAddRiskTreatment.setValueAt(assetName, row+i, 0);
                        //jTableAddRiskTreatment.setValueAt(assetValue, row+i, 1);
                        jTableAddRiskTreatment.setValueAt(atvList.get(i).getThreats().getThreatName(), row+i, 1);
                       jTableAddRiskTreatment.setValueAt(atvList.get(i).getVulnerabilities().getVulnarabilityName(), row+i, 2);
                       try{
                       jTableAddRiskTreatment.setValueAt(riskEvaluation.get(i).getRiskCategory(), row+i, 3);
                       jTableAddRiskTreatment.setValueAt(riskEvaluation.get(i).getRiskExposure(), row+i, 4);


                       //set Invisible columns
                        
                        jTableAddRiskTreatment.setValueAt(riskEvaluation.get(i).getRiskEvaluationId(), row+i, 8);
                        }
                       catch(Exception e){ System.out.println("This means you have not defined Risk Evaluation for All ATV pairs"+e.getMessage());
                                JOptionPane.showConfirmDialog(this, "This means you have not defined Risk Evaluation for All ATV pairs","Error",JOptionPane.DEFAULT_OPTION);
                        }
                        jTableAddRiskTreatment.setValueAt(atvList.get(i).getAssetsThreatsVulnId(), row+i, 9);

                        jTableAddRiskTreatment.setValueAt(atvList.get(i).getThreats().getThreatId(), row+i, 10);
                        jTableAddRiskTreatment.setValueAt(atvList.get(i).getVulnerabilities().getVulnarabilityId(), row+i, 11);
                        jTableAddRiskTreatment.setValueAt(assetId, jTableAddRiskTreatment.getSelectedRow(), 12);

                }

            }

//        } if (jTableAddRiskTreatment.getSelectedColumn()==6 && jTableAddRiskTreatment.getValueAt(row, 1)!=null &&
//                   jTableAddRiskTreatment.getValueAt(row, 4)!=null && jTableAddRiskTreatment.getValueAt(row, 5)!=null){
//
//                float AV = (Float)jTableAddRiskTreatment.getValueAt(row, 1);
//                int L=(Integer)jTableAddRiskTreatment.getValueAt(row, 4);
//                int I=(Integer)jTableAddRiskTreatment.getValueAt(row, 5);
//                float exposure = AV*L*I;
//               // System.out.println("Calculation: "+AV+"*"+L+"*"+I);
//
//                jTableAddRiskTreatment.setValueAt(exposure, row, 6);
//
//        }
        }
    }
}//GEN-LAST:event_jTableAddRiskTreatmentMouseClicked

private void jButtonReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReset2ActionPerformed
    // TODO add your handling code here:
           for(int i=0;i<jTableAddRiskTreatment.getRowCount();i++){
            for(int j=0;j<jTableAddRiskTreatment.getColumnCount();j++){
                jTableAddRiskTreatment.setValueAt(null, i, j);
            }

        }
}//GEN-LAST:event_jButtonReset2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Risk_TreatmentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonReset2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAddRiskTreatment;
    private javax.swing.JTable jTableRisksTreatmentRegister;
    // End of variables declaration//GEN-END:variables
    MyItemListener it;
    CheckBoxHeader cbh;
    CheckBoxHeader rendererComponent;
    DefaultTableModel dtm;
    private javax.swing.JComboBox jComboBoxAssetList = new JComboBox(new DefaultComboBoxModel(getAssetNameList()));

//*****************************************************My methods****************
private RiskTreatment readTableRow(JTable table,int row){
    int i=0;
    if(table == jTableAddRiskTreatment){
     i=2;
    }
    AssetsThreatsVuln asv = new AssetsThreatsVuln();

    RiskTreatment riskTreatment = new RiskTreatment();
    //System.out.println("Searching for Row: "+row+"Column:"+(2-i)+"value: "+;
    try {
    riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().getAssets().setAssetsName((String)table.getValueAt(row, 2-i));

    //riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().getAssets().setAssetsValue((Float)table.getValueAt(row, 3-i));


//    RiskTreatment.getAssetsThreatsVuln().getThreats().setThreatType((String)table.getValueAt(row, 4-i));
    riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().getThreats().setThreatName((String)table.getValueAt(row, 3-i));
    riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().getVulnerabilities().setVulnarabilityName((String)table.getValueAt(row, 4-i));

    riskTreatment.getRiskEvaluation().setRiskCategory((String)table.getValueAt(row, 5-i));
    riskTreatment.getRiskEvaluation().setRiskExposure((Float)table.getValueAt(row, 6-i));
    riskTreatment.setRiskTreatmentApproach((String)table.getValueAt(row, 7-i));
    riskTreatment.setComment((String)table.getValueAt(row, 8-i));
    riskTreatment.setRiskDecisionReason((String)table.getValueAt(row, 9-i));

    riskTreatment.getRiskEvaluation().setRiskEvaluationId((Integer)table.getValueAt(row, 10-i));
    riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().setAssetsThreatsVulnId((Integer)table.getValueAt(row, 11-i));
    riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().getThreats().setThreatId((Integer)table.getValueAt(row, 13-i));

    riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().getVulnerabilities().setVulnarabilityId((Integer)table.getValueAt(row, 11-i));
    riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().getAssets().setAssetId((Integer)table.getValueAt(row, 11-i));
    riskTreatment.getRiskEvaluation().getAssetsThreatsVuln().setAssetsThreatsVulnId((Integer)table.getValueAt(row, 12-i));
    
    if(table==jTableRisksTreatmentRegister){
        riskTreatment.setRiskTreatmentId((Integer)jTableRisksTreatmentRegister.getValueAt(row, 15));
    }
    System.out.println("Data read from the Table is :"+riskTreatment);
    }catch (Exception e){
        System.out.println("Data is not enter correctly please check.");
        JOptionPane.showConfirmDialog(this, "Please check Data.. It Seems values are not correct!","Error",JOptionPane.DEFAULT_OPTION);
    }
    return riskTreatment;

}
private String[] getAssetNameList(){

    String query="Select assetsName from Assets";//where projectId=project.getProjectId()
    String[] assetNamesList = MySQLDAOFactory.getDAOFactory().getAssetsDao().fetchAssetsCol(query);

    if(assetNamesList!=null)
        return assetNamesList;
    assetNamesList[0]="null";
    return assetNamesList;
}
private String[] getVulnList(){

    List<Vulnarabilities> vulList = new ArrayList<Vulnarabilities>();
        vulList=MySQLDAOFactory.getDAOFactory().getVulnDao().fetchVuln("from Vulnarabilities");
    String[] vulnStrList = new String[vulList.size()];
        for(int i=0;i<vulList.size();i++)
            vulnStrList[i]=vulList.get(i).getVulnarabilityName();
        return vulnStrList;
}
private String[] getThreatTypeList(){

        String[] threatsTypeStrList=MySQLDAOFactory.getDAOFactory().getThreatsDao().fetchThreatsCol("Select distinct threatType from Threats");

        if(threatsTypeStrList!=null) {
            for(String i:threatsTypeStrList){
             //   System.out.println("Feched list:"+i);
            }
        }
        return threatsTypeStrList;
}
private String[] getThreatsList(){

    List<Threats> threatList = new ArrayList<Threats>();
        threatList=MySQLDAOFactory.getDAOFactory().getThreatsDao().fetchThreats("from Threats");
    String[] threatsStrList = new String[threatList.size()];
        for(int i=0;i<threatList.size();i++)
            threatsStrList[i]=threatList.get(i).getThreatName();
        return threatsStrList;

}
private void loadTable(JTable table) {

//
        List<RiskTreatment> RiskTreatment = new ArrayList<RiskTreatment>();

        RiskTreatment = MySQLDAOFactory.getDAOFactory().getRiskTreatmentDao().fetchRiskTreatment("from RiskTreatment");
        for(int i=0;i<RiskTreatment.size();i++){
            if ( table.getModel().getRowCount() < RiskTreatment.size() ) {
                @SuppressWarnings("BooleanConstructorCall")
                Object[][] rowData = {{new Boolean(false), null, null, null,null,null}};
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(rowData[0]);
                if ((table.getModel().getRowCount() - 1) == RiskTreatment.size()) {
                    model.setValueAt(i+1,i,1);
                }
            }

            table.getModel().setValueAt(i+1, i, 1);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getAssets().getAssetsName(), i, 2);


            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getThreats().getThreatName(), i, 3);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getVulnerabilities().getVulnarabilityName(), i, 4);

            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getRiskCategory(), i, 5);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getRiskExposure(), i, 6);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskTreatmentApproach(), i, 7);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskDecisionReason(), i, 8);
            table.getModel().setValueAt(RiskTreatment.get(i).getComment(), i, 9);
            //Load Invisible Columns
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getRiskEvaluationId(), i, 10);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getAssetsThreatsVulnId(), i, 11);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getThreats().getThreatId(), i, 12);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getVulnerabilities().getVulnarabilityId(), i, 13);
            table.getModel().setValueAt(RiskTreatment.get(i).getRiskEvaluation().getAssetsThreatsVuln().getAssets().getAssetId(), i, 14);

            if(table==jTableRisksTreatmentRegister){
              table.getModel().setValueAt(RiskTreatment.get(i).getRiskTreatmentId(), i, 15);
            }

           }
        if (RiskTreatment.size() > 0) {
            System.out.println("Database contents delivered...");
        } else {
            System.out.println("Table was empty...");
        }
    }

//------------------ for Select All column---------------------------
    class MyItemListener implements ItemListener {

        public void itemStateChanged(ItemEvent e) {
            Object source = e.getSource();
            if (source instanceof AbstractButton == false) {
                return;
            }
            boolean checked = e.getStateChange() == ItemEvent.SELECTED;
            for (int x = 0, y = jTableRisksTreatmentRegister.getRowCount(); x < y; x++) {
                jTableRisksTreatmentRegister.setValueAt(new Boolean(checked), x, 0);
            }
        }
    }

    class CheckBoxHeader extends JCheckBox implements TableCellRenderer, MouseListener {

        protected int column;
        protected boolean mousePressed = false;
        ItemListener it1;

        public CheckBoxHeader(ItemListener itemListener) {
            setRendererComponent(this);
            this.it1 = itemListener;
            rendererComponent.addItemListener(it1);

            setHorizontalAlignment(SwingConstants.CENTER);
            setOpaque(true);

            // This call is needed because DefaultTableCellRenderer calls setBorder()
            // in its constructor, which is executed after updateUI()
            setBorder(UIManager.getBorder("TableHeader.cellBorder"));



        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (table != null) {
                JTableHeader header = table.getTableHeader();
                if (header != null) {
                    rendererComponent.setForeground(header.getForeground());
                    rendererComponent.setBackground(header.getBackground());
                    rendererComponent.setFont(header.getFont());
                    header.addMouseListener(rendererComponent);
                }
            }
            setColumn(column);
            setBorder(UIManager.getBorder("TableHeader.cellBorder"));
            return rendererComponent;
        }

        protected void setColumn(int column) {
            this.column = column;
        }

        public int getColumn() {
            return column;
        }

        protected void handleClickEvent(MouseEvent e) {
            if (mousePressed) {
                mousePressed = false;

                JTableHeader header = (JTableHeader) (e.getSource());
                JTable tableView = header.getTable();


                TableColumnModel columnModel = tableView.getColumnModel();
                int viewColumn = columnModel.getColumnIndexAtX(e.getX());
                int column = tableView.convertColumnIndexToModel(viewColumn);
                if (viewColumn == this.column && e.getClickCount() == 1 && column != -1) {
                    doClick();
                }
            }
        }

        public void mouseClicked(MouseEvent e) {
            handleClickEvent(e);
            ((JTableHeader) e.getSource()).repaint();
        }

        public void mousePressed(MouseEvent e) {
            mousePressed = true;
        }

        public void mouseReleased(MouseEvent e) {
        }

        public void mouseEntered(MouseEvent e) {
        }

        public void mouseExited(MouseEvent e) {
        }
    }

    public CheckBoxHeader getRendererComponent() {
        return rendererComponent;
    }

    public void setRendererComponent(CheckBoxHeader rendererComponent) {
        //rendererComponent.setText("Check All");

        this.rendererComponent = rendererComponent;
    }

    class MyMouseListener extends MouseAdapter {

        public void mouseClicked(MouseEvent mouseEvent) {
            int checkedCount = 0;
            rendererComponent.removeItemListener(it);
            if (rendererComponent instanceof JCheckBox) {
                boolean[] flags = new boolean[jTableRisksTreatmentRegister.getRowCount()];
                for (int i = 0; i < jTableRisksTreatmentRegister.getRowCount(); i++) {
                    flags[i] = ((Boolean) jTableRisksTreatmentRegister.getValueAt(i, 0)).booleanValue();
//                    //flags[i]=(Boolean)jTableRisksTreatmentRegister.getModel().getValueAt(i, 0);
//                    System.out.println("Checkbox Values are"+jTableRisksTreatmentRegister.getModel().getValueAt(i, 0));
                    if (flags[i]) {
                        checkedCount++;
                    }
                }
                if (checkedCount == jTableRisksTreatmentRegister.getRowCount()) {
                    ((JCheckBox) rendererComponent).setSelected(true);
                }
                if (checkedCount != jTableRisksTreatmentRegister.getRowCount()) {
                    ((JCheckBox) rendererComponent).setSelected(false);
                }
            }
            rendererComponent.addItemListener(it);
            jTableRisksTreatmentRegister.getTableHeader().repaint();
        }
    }

//------------------- code fo Select All Column Ends here -------------

//*************************************Methods ends*****************************



}
