package com.rts.admin;

import com.rts.dao.daofactory.MySQLDAOFactory;
import com.rts.dao.interfaces.BusinessUnitDAO;
import com.rts.dao.interfaces.ProjectsDAO;
import com.rts.pojoclasses.BusinessUnitPojo;
import com.rts.pojoclasses.ProjectSpoc;
import com.rts.pojoclasses.Projects;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeleteProject.java
 *
 * Created on Aug 31, 2012, 5:55:31 PM
 */

/**
 *
 * @author bhandrah
 */
public class DeleteProject extends javax.swing.JFrame {

    BusinessUnitDAO budao=MySQLDAOFactory.getDAOFactory().getBUDAO();
    ProjectsDAO projectsDAO= MySQLDAOFactory.getDAOFactory().getProjectsDAO();
    List <Projects> projectsList;
    Projects projects,projectToPass;
    /** Creates new form DeleteProject */
    public DeleteProject() {
        initComponents();
        projects= new Projects();
        projectToPass= new Projects();
         Object[] bu=budao.getBUFromDb();
        DefaultComboBoxModel model=new DefaultComboBoxModel(bu);
        jComboBox1.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Business Unit Name : ");

        jButton1.setText("Delete");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Project Name : ");
        jLabel2.setEnabled(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jComboBox1, 0, 124, Short.MAX_VALUE)))))
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox2.setEnabled(true);
        jLabel2.setEnabled(true);
        jButton1.setEnabled(true);
        
         String str = (String)jComboBox1.getSelectedItem();
           int buid = budao.getBuForProjectFromDb(str);
        BusinessUnitPojo bup = new BusinessUnitPojo();
        bup.setBuId(buid);
        bup.setBuName(str);
        projectToPass.setBusinessUnit(bup);
        //int buid = budao.getBuForProjectFromDb(str);
        projectsList = projectsDAO.getProjectFromDb(str);
         Object [] projectArray=new Object[10];
         for (int i=0;i<projectsList.size();i++)
         {
             projects = (Projects) projectsList.get(i);
             projectArray[i] = projects.getProjectName();

         }
       // Object [] projectArray=projectsList.toArray();
        DefaultComboBoxModel model=new DefaultComboBoxModel(projectArray);
        jComboBox2.setModel(model);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //String projectName=(String)jComboBox2.getSelectedItem();
        if(JOptionPane.showConfirmDialog(this, "Do you want to confirm the deletion of Project?", "Delete Project", JOptionPane.YES_NO_OPTION) == 0)
        {
            projectsDAO.deleteProjectFrmDb(projectToPass);
            jComboBox1ActionPerformed(evt);
        
        }
        else
        {
            jComboBox2ActionPerformed(evt);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:


        String projectName = (String)jComboBox2.getSelectedItem();
         int projectId=0;
         ProjectSpoc projectSpoc =  new ProjectSpoc();
         
         for (int i=0;i<projectsList.size();i++)
         {
             projects = (Projects) projectsList.get(i);
           
             if(projectName.equals(projects.getProjectName()))
             {
                  jLabel2.setEnabled(true);
           
                 jLabel1.setEnabled(true);
                 projectId= projects.getProjectId();
                projectToPass.setProjectId(projectId);
                 projectToPass.setProjectName(projectName);
                 projectToPass.setProjectOwner(projects.getProjectOwner());
             }


         }

      //   projectsDAO.deleteProjectFrmDb(projectToPass);
    

        /*List<ProjectSpoc>projectSpocs= projectsDAO.getProjectSpocsFromDb(projectId);
        for(int i=0 ; i<projectSpocs.size();i++)
        {
            projectSpoc = (ProjectSpoc) projectSpocs.get(i);

        }*/


    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
